### ISSUE TITLE
how to show readonly mode ?

### ISSUE THREAD

**Issue by larrycai** [tobegit3hub/pirate#11]
In issue #6, the readonly mode (`PIRATE_MODE`) is supported, but it doesn't reflect in the UI

How to achieve it ?

1. grey the DELETE button directly and show tips for the button // suggested, need codes in UI
2. display the error message in UI // no big changes for UI

**Comment by sdd330** [comment]
Since it works on your side, we can close the issue now

**Comment by larrycai** [comment]
wait for a while, we may need to improve the UI for the readonly. Indicate
somewhere in GUI to show it is READONLY mode (a.k.a GUEST), another shall
be "ADMIN" mode

​

**Comment by larrycai** [comment]
resolves by PR #14
