### ISSUE TITLE
link to external webpage for image information

### ISSUE THREAD

**Issue by larrycai** [tobegit3hub/pirate#13]
so far the information for each image from API is quite limited, it will be good to link to external page for the information, like wiki system. 

Default could be https://registry.hub.docker.com/u/  

So `library/maven` => https://registry.hub.docker.com/u/library/maven/

If the external webpage is defined, then it goes to like

`larrycai/nginx-pirate` => http://wiki.example.com/docker/larrycai/nginx-pirate

env: 

* PIRATE_DEFAULT_HUB=enabled : enable the link 
* PIRATE_EXTERNAL_DOC_URL=http://wiki.example.com/docker/

Could add extra button [DOC] besides delete for this.

**Comment by sdd330** [comment]
Shall we use PIRATE_DOC_REF instead of PIRATE_EXTERNAL_DOC_URL
Also the requirement might be updated a little

**Comment by larrycai** [comment]
that's ok

On Thu, Jan 15, 2015 at 8:10 AM, Yang Leijun <notifications@github.com>
wrote:

> Shall we use PIRATE_DOC_REF instead of PIRATE_EXTERNAL_DOC_URL
> Also the requirement might be updated a little
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tobegit3hub/pirate/issues/13#issuecomment-70018399>.
>



-- 
True software development embraces consistent inconsistency.
blog: http://larrycaiyu.com/blog (en), http://larrycaiyu.com (chinese)

**Comment by larrycai** [comment]
related #18 , it can be solved there directly
