### ISSUE TITLE
`ADD . /app` add .git directory in Dockerfile

### ISSUE THREAD

**Issue by larrycai** [tobegit3hub/pirate#29]
`ADD . /app` or `Add . /go/src/github.com/tobegit3hub/pirate/` adds the `.git` directory into docker image, it looks not good. Do we really need git history there ?

**Comment by larrycai** [comment]
@tobegit3hub do you want `.git` directory into docker image ?

**Comment by tobegit3hub** [comment]
Of course we don't need it. Maybe adding the `.dockerignore` could solve it :smiley:

**Comment by tobegit3hub** [comment]
It seems already in `.dockerignore` https://github.com/tobegit3hub/pirate/blob/master/.dockerignore#L1.

**Comment by larrycai** [comment]
`.dockerignore` is to ingore those files during `docker build`

Quick test it, we can use

    ADD [^.]* /go/src/github.com/tobegit3hub/pirate/
    ADD README.md BUILD.LOG Dockerfile /app/

**Comment by larrycai** [comment]
Not fixed yet, post in sto: http://stackoverflow.com/questions/28079872/how-to-add-all-files-directories-except-hidden-directory-like-git-in-dockerfile

**Comment by tobegit3hub** [comment]
Open the issue for docker? It's not a big deal. Let's push docker to fix it?

**Comment by larrycai** [comment]
Agree, just keep it for a while to see whether it can be solved. If it is
the bug in docker, surely we just refer and close it.

You can open the issue for me in docker if you think it is docker issue ;-)
?

On Thu, Jan 22, 2015 at 10:03 AM, tobe <notifications@github.com> wrote:

> Open the issue for docker? It's not a big deal. Let's push docker to fix
> it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tobegit3hub/pirate/issues/29#issuecomment-70959631>.
>



-- 
True software development embraces consistent inconsistency.
blog: http://larrycaiyu.com/blog (en), http://larrycaiyu.com (chinese)

**Comment by larrycai** [comment]
little strange, it is there when I checked into docker image layer by layer once. Now it disappear. Close it again.

**Comment by larrycai** [comment]
.dockerignore works for ADD as well, this is good notice. (ADD works on all contexts send to docker daemon, so it shall work)
